CREATE DATABASE  IF NOT EXISTS `jsp` /*!40100 DEFAULT CHARACTER SET utf8 */;
USE `jsp`;

DROP TABLE IF EXISTS `role`;

CREATE TABLE `role` (
  `ROLE_ID` bigint(22) NOT NULL AUTO_INCREMENT,
  `ROLE_NAME` varchar(50) NOT NULL,
  `ROLE_DESCRIPTION` varchar(200) DEFAULT NULL,
  PRIMARY KEY (`ROLE_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8;

INSERT INTO `role` VALUES (1,'admin',NULL),(2,'user',NULL);


DROP TABLE IF EXISTS `user`;
CREATE TABLE `user` (
  `USER_ID` bigint(22) NOT NULL AUTO_INCREMENT COMMENT 'RUNNING NUMBER',
  `USER_USERNAME` varchar(50) NOT NULL COMMENT 'RUNNING NUMBER',
  `USER_PASSWORD` varchar(50) NOT NULL COMMENT 'RUNNING NUMBER',
  `USER_FIRSTNAME` varchar(50) DEFAULT NULL,
  `USER_LASTNAME` varchar(50) DEFAULT NULL,
  `ROLE_ID_FK` bigint(22) NOT NULL,
  PRIMARY KEY (`USER_ID`),
  KEY `ROLE_ID_FK_idx` (`ROLE_ID_FK`),
  CONSTRAINT `ROLE_ID_FK` FOREIGN KEY (`ROLE_ID_FK`) REFERENCES `role` (`ROLE_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8;

INSERT INTO `user` VALUES (1,'admin123','123456','Pratya','Yeekhaday',1),(2,'user123','123456','John','Maxel',2);